// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpnQOVru-EdSqdfmL-PihnIruYE_uAcKY',
    appId: '1:130036512833:android:fba45c052faae70cc22ec0',
    messagingSenderId: '130036512833',
    projectId: 'wevoride-21bb8',
    databaseURL: 'https://wevoride-21bb8-default-rtdb.firebaseio.com',
    storageBucket: 'wevoride-21bb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCoUVLN6QRRJU6DJdsZakmrs5FScBCpQ4',
    appId: '1:130036512833:ios:569c4463232eceefc22ec0',
    messagingSenderId: '130036512833',
    projectId: 'wevoride-21bb8',
    databaseURL: 'https://wevoride-21bb8-default-rtdb.firebaseio.com',
    storageBucket: 'wevoride-21bb8.firebasestorage.app',
    androidClientId: '130036512833-qoaf7ea7i2tr0jd8uutd674ra6hmv98m.apps.googleusercontent.com',
    iosClientId: '130036512833-sgov411jgk3d3rvvqk447dfmq0bokn2j.apps.googleusercontent.com',
    iosBundleId: 'com.wevoride',
  );

}